version: '3'
services:
  api:
    image: sunilvb/rest-api-tutorial
    build: .
    networks:
      - backend
    ports:
      - "3600:3600"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    networks:
      - backend
    ports:
      - "27017:27017"

  web-cli:
    image: sunilvb/rest-api-tutorial
    links:
      - mongo
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
